baseURL: https://blogong.github.io
languageCode: en-us
title: Hugo
theme: mini
paginate: 3

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: UA-123-45
disqusShortname: nodejh


markup:
  highlight:
    guessSyntax: true
    style: emacs

params:
  author: nodejh
  bio: Software Engineer
  description: My Blog
  enableComments: true
