baseURL: https://blogong.github.io
languageCode: en-us
title: Hugo
theme: mini
paginate: 3

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: UA-123-45
disqusShortname: nodejh


markup:
  highlight:
    guessSyntax: true
    style: emacs


social:
  github: https://github.com/nodejh
  twitter: https://twitter.com/nodejh
  stackoverflow: https://stackoverflow.com/users/4518882/nodejh


params:
  author: nodejh
  bio: Software Engineer
  description: My Blog
  enableRSS: true
  enableComments: true
  enableGoogleAnalytics: true
